Mobile Conference/Controllers/WidgetController.cs
using System.Web.UI.WebControls.Expressions;
using Castle.Core.Internal;
using MobileConference.Enums;
using MobileConference.Filters;
using MobileConference.GlobalData;
using MobileConference.Helper;
using MobileConference.Interface;
using MobileConference.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileConference.Controllers
{
    public class WidgetController : Controller
    {
        private readonly IUserRepository userRepository;
        private readonly IEventRepository eventRepository;
        private readonly IIdeasRepository ideasRepository;
        private readonly IImageRepository imageRepository;
        private readonly IImageManager imageManager;
        private readonly ICapchaManager capchaManager;

        public WidgetController(IUserRepository userRepository, IEventRepository eventRepository,
            IIdeasRepository ideasRepository, IImageRepository imageRepository, IImageManager imageManager,
            ICapchaManager capchaManager)
        {
            this.userRepository = userRepository;
            this.eventRepository = eventRepository;
            this.ideasRepository = ideasRepository;
            this.imageRepository = imageRepository;
            this.imageManager = imageManager;
            this.capchaManager = capchaManager;
        }


        public PartialViewResult AccountInfo()
        {
            ViewBag.WithAvatar = false;
            ViewBag.IsAuth = false;
            if (User == null || !User.Identity.IsAuthenticated)
            {
                ViewBag.IsAuth = false;
                return PartialView();
            }
            var user = ProfileModel.Current;
            ViewBag.FirstName = user.FirstName??string.Empty;
            ViewBag.LastName = user.LastName??string.Empty;
            ViewBag.IsAuth = true;
            ViewBag.Id = user.Id;
            ViewBag.WithAvatar = user.Avatar != null;
            if (user.FirstName.IsNullOrEmpty() && user.LastName.IsNullOrEmpty())
            {
                ViewBag.FirstName = user.Login;
            }

            return PartialView(user);
        }

        #region Widget for start page

        [ChildActionOnly]
        public PartialViewResult Adwards()
        {
            var currentEvent = EventModel.Current;
            List<AwardModel> adwards = null;
            if (currentEvent != null)
            {
                adwards = AwardModel.GetForEvent(EventModel.Current.Id);                
            }
            return PartialView(adwards);
        }

        [ChildActionOnly]
        public PartialViewResult RecentStage()
        {
            var stages = new List<EventModelWithOrder>();
            var currentEvent = EventModel.Current;
            if (currentEvent != null)
            {
                stages = currentEvent.GetCurrentChild();
            }
            return PartialView(stages);            
        }


        public PartialViewResult ExpertList()
        {
            List<ProfileModel> experts = userRepository.GetExpertsToStartPage(GlobalValuesAndStrings.ExpertCountOnStartPage);
            return PartialView(experts);
        }


        public PartialViewResult RecentProject(int? platformId = null, int? groupIdeaId = null)
        {
            var ideas = ideasRepository.GetAllIdeas(GlobalValuesAndStrings.FirstPageCount,
                platform: platformId, ideasGroup: groupIdeaId, take: GlobalValuesAndStrings.ProjectCountOnStartPage, remix: true)
                .Take(GlobalValuesAndStrings.ProjectCountOnStartPage).AsQueryable().ToModel();
            
            var projects = ideas.Select(idea => idea.GetIdeaWithPlatform(platformId)).ToList();
            return PartialView(projects);
        }


        public PartialViewResult RecentMaterial(int? materialPlatformId = null)
        {
            var materials = eventRepository.GetMaterials(materialPlatformId).OrderBy(x => Guid.NewGuid())
                .Take(GlobalValuesAndStrings.MaterialCountOnStartPage).AsEnumerable().ToModel();
            return PartialView(materials);
        }


        [ChildActionOnly]
        public PartialViewResult SponsorList()
        {
            var sponsors = userRepository.GetSponsorIds().Select(CompanyModel.GetById).ToList();
            return PartialView(sponsors);
        }


        [ChildActionOnly]
        public PartialViewResult InfoPartnerList()
        {
            var infoPartners = userRepository.GetInfoPartnerIds().Select(CompanyModel.GetById).ToList();
            return PartialView(infoPartners);
        }

        #endregion //Widget for start page

        #region Widget for Materials,Projects, Experts and Events Pages


        [Authorize]
        public PartialViewResult MaterialsWithPlatformDescription(int? materialPlatformId = null, string search = "")
        {
            PlatformModel model = materialPlatformId == null ? null : PlatformModel.ForPlatform((int)materialPlatformId);
            ViewBag.search = search;
            return PartialView(model);
        }


        [Authorize]
        public PartialViewResult AllMaterials(int? materialPlatformId = null, int page = GlobalValuesAndStrings.FirstPageCount,
            string search = "")
        {
            var materials = eventRepository.GetMaterials(materialPlatformId, null,search)
                .OrderByDescending(m => m.AddedDate).ToPagedList(page, OptionModel.Current.ItemPerPage);
            ViewBag.materialPlatformId = materialPlatformId;
            ViewBag.search = search;
            return PartialView(materials);
        }


        public PartialViewResult AllProject(int? platformId = null, int? groupIdeaId = null,
            int page = GlobalValuesAndStrings.FirstPageCount, string search = "")
        {
            List<int> currentUserProjects = null;
            int emptyProjectAtTheBegining = 0;
            if (User.Identity.IsAuthenticated)
            {
                var user = ProfileModel.Current;
                if (user != null)
                {
                    if (user.Role == RoleName.Student)
                    {
                        if (user.MemberIdeas.Any())
                        {
                            currentUserProjects = user.MemberIdeas.Select(i=>i.Id).ToList();
                        }
                        else
                        {
                            if (!OptionModel.Current.ForbiddenProjectRegistration)
                            {
                                emptyProjectAtTheBegining = GlobalValuesAndStrings.ProjectsPerOneStudentCount;
                            }
                        }
                    }
                    
                    if (user.Role == RoleName.Mentor)
                    {
                        if (user.MemberIdeas.Any())
                        {
                            currentUserProjects = user.MemberIdeas.Select(i => i.Id).ToList();
                        }
                    }
                }
            }
            var ideas = ideasRepository.GetAllIdeas(page, platform: platformId, ideasGroup: groupIdeaId, search: search,
                topIds: currentUserProjects, withEmptyProjects: emptyProjectAtTheBegining);
            ViewBag.platformId = platformId;
            ViewBag.groupIdeaId = groupIdeaId;
            ViewBag.search = search;
            ViewBag.emptyProject = emptyProjectAtTheBegining;
            return PartialView(ideas);
        }

        /// <summary>
        /// Get previous, next or all events
        /// </summary>
        public PartialViewResult RecentEvents(EventListType categoriesEvent = EventListType.All,
            int page = GlobalValuesAndStrings.FirstPageCount)
        {
            var events = eventRepository.GetNeededLevelEvents(EventModel.Current.Id, GlobalValuesAndStrings.NewsLevelInEvent,
                categoriesEvent, false, page);
            ViewBag.categories = categoriesEvent;
            return PartialView(events);
        }

        public ActionResult Experts(int page = GlobalValuesAndStrings.FirstPageCount)
        {
            var experts = userRepository.GetAllUsers(page, string.Empty, false, RoleName.Expert);
            return PartialView(experts);
        }


        [ForbiddenElse("Administrator", "InfoPartner", "Expert", "Sponsor")]
        public ActionResult SelectCompanyPartial(int page = GlobalValuesAndStrings.FirstPageCount, string search = "", string login = null)
        {
            var user = ProfileModel.Current;
            if (user == null) return PartialView(null);
            bool withHiddenCompanies = (user.Role == RoleName.Administrator);
            var companies = userRepository.GetAllCompanies(search, withHiddenCompanies).OrderByDescending(c => c.IsShowed)
                .ThenBy(c=>c.Rank==null).ThenBy(c=>c.Rank).ToPagedList(page, OptionModel.Current.ItemPerPage);
            ViewBag.page = page;
            ViewBag.search = search;
            ViewBag.login = login;
            return PartialView(companies);
        }

        public ActionResult EventForStagePartial(int stageId, int page = GlobalValuesAndStrings.FirstPageCount)
        {
            ViewBag.page = page;
            ViewBag.stageId = stageId;
            var events = eventRepository.GetEventForStage(stageId, page);
            return PartialView(events);            
        }

        public ActionResult ShowEventForStagePartial(int stageId, int childrenCount, int page = GlobalValuesAndStrings.FirstPageCount,
            bool isShowing = false)
        {
            ViewBag.page = page;
            ViewBag.stageId = stageId;
            ViewBag.childrenCount = childrenCount;
            ViewBag.isShowing = isShowing;
            return PartialView();
        }

        #endregion //Widget for Materials,Projects, Experts and Events Pages

        #region Widget for Ideas

        [ChildActionOnly]

Mobile Conference/Views/Widget/AddPhotoToMessageInChat.cshtml
@using MobileConference.Enums
@using MobileConference.Helper
<script>
    ClearImageArea();
</script>
<div class="container_12 imageLabel"  data-pic="picture">
    <div class="grid_9 alpha">
        <div class="topContainer center">
            <h3>
                @Html.ImageLabel("Пожалуйста выделите область для сохранения", "picture")  
            </h3>              
            @Html.ImageLoader("userLoader", "picture", Html.StandardImageFileName(true), StandardRatioType.IdeaRatio)
        </div>
    </div>

    <div class="grid_3 omega">
        <h3>
            @Html.ImageLabel("Вы можете посмотреть, как будет выглядеть ваша фотография на сайте", "picture")                
        </h3>
        @Html.ImagePreview("preview", "picture", StandardRatioType.IdeaRatio)
    </div>
</div>

Mobile Conference/Views/Widget/AllProject.cshtml
@using MobileConference.Models
@using MobileConference.Helper
@model PagedList.IPagedList<Idea>


    @{ Html.ClearGridClass(); }
    <div class="container_12 brickBlocks">
        @if ((int) ViewBag.emptyProject > 0)
        {
             <div class="@Html.GridClass(3) emptyProject" id="blankForNewProject">
                 @Html.ActionLink("Создать проект", "CreateNew", "Ideas") 
            </div>
        }
        @if (!Model.Any() && (int)ViewBag.emptyProject<1)
        {
            <div class="grid_4">
                <div>Извините, по вашему запросу еще нет проектов</div>
            </div>
        }
        else
        {
            foreach (var idea in Model.ToModel())
            {
                <div class=" @Html.GridClass(3)">
                    @Html.Partial("RenderIdea", idea.GetIdeaWithPlatform((int?) ViewBag.platformId))
                </div>
            }
        }
    </div>

<div class="container_12">
    <div class="grid_6">
        @Html.Pager(Model,page=>Url.Action("AllProject",new
        {
            page, platformId = (int?)ViewBag.platformId, search = (string)ViewBag.search,  groupIdeaId = (int?)ViewBag.groupIdeaId
        }))        
    </div>
</div>

Mobile Conference/Views/Widget/ChatMessageSender.cshtml
@using MobileConference.Enums
@using MobileConference.Helper
@using MobileConference.Models
@model CommentModel

@if (((PermissionType)ViewBag.permission).HasFlag(PermissionType.UseChat))
{
    @Html.Hidden("chatUpdate", Url.Action("GetLastUpdateForComment","Ideas",new {ideaId = (int)ViewBag.ideaId}))
    
    <div class="container_12 topContainer" id="chatSenderBlock">
        <div class="grid_12 bottomBorder">
            <div class="grid_1">
                @Html.AvatarForUser(ProfileModel.Current.Id)
            </div>
            <div class ="grid_6">
                @using (Html.BeginForm("ChatMessageSender", "Widget", FormMethod.Post, new {@class = "withAjax", id = "chatForm"}))
                {
                    @Html.Hidden("page", (int) ViewBag.page)
                    @Html.Hidden("ideaId", (int) ViewBag.ideaId)
                    @Html.TextAreaFor(m => m.Message, new {rows = "8", cols = "60"})
                    <input type="submit" value="Отправить" class="customButton grey mediumSizeButton"/>
                }
            </div>
            <div class="grid_4 addPhotos ajaxHere">
                @Html.Action("ChatPhotoSection","Ideas", new {ideaId = (int)ViewBag.ideaId})
            </div>
        </div>
    </div>
}
@if (((PermissionType) ViewBag.permission).HasFlag(PermissionType.ShowChat))
{
    <div class="container_12 topContainer">
        <div class="grid_8 ajaxHere paginationWrapper" id="chatBlock">
            @Html.Action("ShowAllComments", "Widget", new {ideaId = (int) ViewBag.ideaId, page = (int) ViewBag.page})
        </div>
    </div>
}

Mobile Conference/Views/Widget/HorizontalMenu.cshtml
@using MobileConference.Models
@model IList<CustomMenuItem>
<div id="menu">
    @foreach (CustomMenuItem item in Model)
    {
        @Html.ActionLink(item.Title,item.Action,item.Controller,item.Param, new {@class="itemMenu"})
    }
</div>

Mobile Conference/Views/Widget/ListGroupMember.cshtml
@using MobileConference.Helper
@using MobileConference.Models
@model List<ProfileModel>

@if (ViewBag.mentorLogin != null)
{
    <h3>Ментор пректа</h3>        
    <p>@Html.ProfileLik((string)ViewBag.mentorLogin)</p>
}
@if (ViewBag.leaderLogin != null)
{
    <h3>Капитан команды</h3>        
    <p>@Html.ProfileLik((string)ViewBag.leaderLogin)</p>
}
<h3>Участники команды</h3>
@foreach (var student in Model)
{
    if (ViewBag.leaderLogin == null || student.Login != (string) ViewBag.leaderLogin)
    {
        <p>@Html.ProfileLik(student.Login)</p>
    }
}

Mobile Conference/Views/Widget/MaterialComments.cshtml
@using MobileConference.GlobalData
@using MobileConference.Helper
@using MobileConference.Models
@model MobileConference.Models.MaterialModel
<p>
    @Model.MaterialCountPrettyTitle
    @Html.ActionLink((!ViewBag.IsShowing)?Model.ShowMaterialMessage:GlobalValuesAndStrings.CloseCommentsTitle, 
        "MaterialComments","Widget", new{materialId = Model.Id, IsShowing = !ViewBag.IsShowing}, new{@class="showComments"})
</p>
@if (ViewBag.IsShowing)
{
    <div class="paginationWrapper">
        @Html.Action("ShowMaterialComments","Widget",new{materialId = Model.Id,page = (int)ViewBag.page})
    </div>
    <div class="bottomBorder grid_9"></div>
    <div class="grid_8">
        <div class="grid_1">
            @Html.AvatarForUser(ProfileModel.Current.Id)
        </div>
        <div class ="grid_6">
            @using (Html.BeginForm("AddMaterialComment", "Widget", FormMethod.Post, new{@class = "withAjax"}))
            {
                @Html.TextArea("Message", new {rows="6", cols="60"})
                @Html.Hidden("materialId",(int)ViewBag.materialId)
                <br/>
                <input type="submit" value="Комментировать" class="customButton grey mediumSizeButton"/>
            }
        </div>
    </div>    
}

Mobile Conference/Views/Widget/RecentStage.cshtml
@model List<MobileConference.Models.EventModelWithOrder>

@if (Model.Any())
{
    <div class="fullBlock">
        <div class="container_12">
            <a class="withoutDecoration" href="@Url.Action("Stages","Home")">
            
                <div id="stages">
                    @if (Model.Count == 1)
                    {
                        <div class="grid_4 prefix_4 alpha phase">
                            @Html.Partial("RenderStage", Model[0])
                        </div>
                    }
                    @if (Model.Count == 2)
                    {
                        <div class="grid_4 prefix_2 alpha phase">
                            @Html.Partial("RenderStage", Model[0])
                        </div>
                        <div class="grid_4 suffix_2 omega phase">
                            @Html.Partial("RenderStage", Model[1])
                        </div>
                    }
                    @if (Model.Count > 2)
                    {
                        <div class="grid_4 alpha phase">
                            @Html.Partial("RenderStage", Model[0])
                        </div>
                        <div class="grid_4 phase">
                            @Html.Partial("RenderStage", Model[1])
                        </div>
                        <div class="grid_4 omega phase">
                            @Html.Partial("RenderStage", Model[2])
                        </div>
                    }
                </div>
            </a>
        </div>
    </div>
}

Mobile Conference/Views/Widget/RotateImage.cshtml
<p>@ViewBag.fileName</p>

Mobile Conference/Views/Widget/ShowAllComments.cshtml
@using MobileConference.Enums
@using MobileConference.Helper
@using MobileConference.Models
@using MobileConference.Models
@using PagedList.Mvc
@model PagedList.IPagedList<Comment>

@Html.Hidden("chatTo", Url.Action("ShowAllComments","Widget",new {ideaId = (int)ViewBag.ideaId, 
                    page = (int)ViewBag.page}))

@if (Model != null && Model.Any())
{
    foreach (var comment in Model.ToModel())
    {
        @Html.Action("DescribeComment", "Widget", new { comment, page = (int)ViewBag.page })
    }
    <div class="grid_6">
            @Html.Pager(Model, page => Url.Action("ShowAllComments", "Widget", new { page, ideaId = (int)ViewBag.ideaId, 
                commentType =  (CommentModelType)ViewBag.commentType }))        
    </div>
}
else
{
    if ((int) ViewBag.page == 1)
    {
        <div class="grid_6">
            <i>Сообщений нет</i>
        </div>
    }
}

Mobile Conference/Views/Widget/ShowEventForStagePartial.cshtml
@using MobileConference.GlobalData
@if (ViewBag.childrenCount > 0)
{
    <p>
        @Html.ActionLink((!ViewBag.isShowing) ? "расписание (" + ((int)ViewBag.childrenCount)+")" : GlobalValuesAndStrings.CloseCommentsTitle,
            "ShowEventForStagePartial", "Widget", new
            {
                stageId = (int) ViewBag.stageId, isShowing = !ViewBag.isShowing, childrenCount = (int) ViewBag.childrenCount
            }, new {@class = "showComments"})
    </p>
    if (ViewBag.isShowing)
    {
        <div class="paginationWrapper">
            @Html.Action("EventForStagePartial", "Widget", new {stageId = (int) ViewBag.stageId, page = (int) ViewBag.page})
        </div>
    }
}

Mobile Conference/Views/Widget/ShowIdeaPhotos.cshtml
@using MobileConference.Enums
@using MobileConference.Helper
@using MobileConference.Models
@model List<MobileConference.Models.PictureNameModel>
<div>
    @if (Model == null || !Model.Any())
    {
        <div class="container_12">
            @if (((IdeaWithPermission) ViewBag.idea).Permission.HasFlag(PermissionType.ShowPhotos))
            {
                <p>Фотографий пока нет.</p>
            }
            else
            {
                <p>У вас нет прав на просмотр фотоальбома.</p>
            }
            <div class="pictureJustLoadingProgress @Html.GridClass(2)"></div>
        </div>
    }
    else
    {
        Html.ClearGridClass();
        <div class="container_12 topContainer brickBlocks">
            <div class="photoGroup">       
                @foreach (var picture in Model)
                {
                    <div class="@Html.GridClass(2) photoContainer">
                
                        <a href="@Html.UrlForPicture(picture)" class="withoutDecoration">
                            @Html.DrawPicture(picture, false, "photo", null, true)
                            <br/>
                        </a> 
                        <div class="photoRemove">
                            @if (((IdeaWithPermission) ViewBag.idea).Permission.HasFlag(PermissionType.DeletePhotos))
                            {
                                using (@Html.BeginForm("RemoveImageFromPhototgallery", "Ideas", FormMethod.Post, new {@class = "withAjax"}))
                                {
                                    @Html.Hidden("ideaId", (int) ViewBag.ideaId)
                                    @Html.Hidden("url", Html.UrlForPicture(picture))
                                    <input type="submit" value="Удалить" class="customButton grey"/>
                                }
                            }
                        </div>
                    </div>
                }
                <div class="pictureJustLoadingProgress @Html.GridClass(2)"></div>

            </div>
        </div>
    }
</div>
@if (ViewBag.error)
{
    <div class="loadError"></div>
}

Mobile Conference/Views/Widget/ShowMaterialComments.cshtml
@using MobileConference.Helper
@using MobileConference.Models
@using MobileConference.Models
@model PagedList.IPagedList<Comment>

@if (Model == null || !Model.Any())
{
    <p>Комментариев пока нет</p>
}
else
{
    <a class="anchorHere"></a>    
    foreach (var comment in Model.ToModel())
    {
        <div class="grid_9 topContainer">        
            @Html.Action("DescribeComment","Widget", new {comment, page = (int)ViewBag.page})
        </div>
    }  
    <div class="grid_8 topContainer">
        @Html.Pager(Model,page=>Url.Action("ShowMaterialComments",new{page, materialId = (int)ViewBag.materialId }))
    </div>
}

Mobile Conference/Views/Widget/ShowPicturesForEvent.cshtml
@using MobileConference.Helper
@model List<MobileConference.Models.PictureNameModel>
<script>UpdatePictureBlocks()</script>
<div>
    @if (Model != null && Model.Any())
    {
        Html.ClearGridClass();
        if (!ViewBag.withoutTitle)
        {
            @Html.FloatTitle("Фотоотчет", true)
        }
        <div class="photoGroup topContainer">
            @foreach (var photo in Model)
            {
                if (Html.IsUrlValid(photo))
                {
                    <div class="@Html.GridClass(2) photoContainer">
                        <a href="@Html.UrlForPicture(photo)" class="withoutDecoration">
                            @Html.DrawPicture(photo, false, "photo", null, true)
                            <br/>
                        </a>
                        @if ((bool) ViewBag.isAdmin)
                        {
                            <div class="photoRemove">
                                @using (@Html.BeginForm("RemoveImageFromPhototgallery", "Admin", FormMethod.Post, new {@class = "withAjax"}))
                                {
                                    @Html.Hidden("eventId", (int) ViewBag.eventId)
                                    @Html.Hidden("url", Html.UrlForPicture(photo))
                                    <input type="submit" value="Удалить" class="customButton grey"/>
                                }
                            </div>
                        }
                    </div>
                }
            }
            <div class="pictureJustLoadingProgress @Html.GridClass(2)"></div>
        </div>
    }
</div>

Mobile Conference/Views/Widget/UsersForInviting.cshtml
@using MobileConference.Helper
@using MobileConference.Models
@using MobileConference.Models
@using PagedList.Mvc
@model PagedList.IPagedList<UserProfile>

@if (Model != null && Model.Count > 0)
{
    Html.ClearGridClass();
    foreach (UserProfile user in Model)
    {
        <div class="@Html.GridClass(3) borderBlock">
            @Html.Action("DescribeInvitedUser", "Widget", new
       {
           idea = (IdeasModel)ViewBag.idea,
           user = user.ToModel(),
           ViewBag.page,
           ViewBag.search

       })
        </div>
    }
    <div class="grid_6 suffix_6">
        @Html.Pager(Model, page => Url.Action("UsersForInviting", new
   {
       page,
       search = (string)ViewBag.search,
       ideaId = ((IdeasModel)ViewBag.idea).Id
   }))
    </div>
}